### ISSUE TITLE
Questions about the task of the logo for RekepKueKeringPraktis

### ISSUE THREAD

**Issue by richardbmx** [iqbalhood/ResepKueKeringPraktis#3]
hello I would like to ask you some questions about the task of the logo for your application, I would like to know if you have some pictures of the products that you make of resposteria or some pictures of traditional Indonesian respoteria this in order to achieve a better inspiration to perform. Another question is whether the application is for product sales or just to search and find recipes.

**Comment by iqbalhood** [comment]
Cake is a food that is eaten during the celebration in Indonesia. The logo must contain letter (Resep Kue Kering Praktis) explaining that it is a recipe application. And use the color I have explained in the post.

You can find indonesian pastry image by typing "kue khas indonesia in google search"
![screen shot 2018-03-25 at 6 27 57 pm](https://user-images.githubusercontent.com/1563756/37874486-59971d64-305a-11e8-959a-1e7dd3a237ad.png)
