### ISSUE TITLE
New logo resep Kue Kering

### ISSUE THREAD

**Issue by familqasimov** [iqbalhood/ResepKueKeringPraktis#4]
Hi sir Iqbal. I've created a logo that suits your request. I think you will like it.

![untitled-1](https://user-images.githubusercontent.com/36432269/37998839-528598e2-3231-11e8-877e-47202070579e.jpg)

**Comment by iqbalhood** [comment]
I Don't Think So, Please Modify logo like the logo on this link . 
https://id.pinterest.com/stephendarrigan/cookie-logo/?lp=true
Dont Copy Paste It, Be aware of Studio font policy.
