### ISSUE TITLE
Proposal For Copywriting

### ISSUE THREAD

**Issue by ewuoso** [iqbalhood/ResepKueKeringPraktis#7]
Hello i went through your project and i want to say it is very nice. However i noticed you are missing out some important details like gaq, about us and privacy policy which users will be looking forward too. If you dont mind i can write that for you

contact me
email ewuosoolusesi@gmail.com

steemit.com/@ewuoso

**Comment by iqbalhood** [comment]
Off course just create your contribution and email it to me
iqbalhood@gmail.com

**Comment by ewuoso** [comment]
how do i get the english version of the app?

**Comment by iqbalhood** [comment]
The menu of the app already speaks english, but the application contents yet, I have not developed there yet, I am more interested in improving features to improve user engagement such as submit recipes and push notification

**Comment by ewuoso** [comment]
i will come up with something

**Comment by iqbalhood** [comment]
Hey,  I Have approve your Pull request .
